version: "3.8"

services:
  db:
    image: steven32/mariadb-asir:10.6
    container_name: glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - glpi_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  glpi:
    image: steven32/glpi-asir:latest
    container_name: glpi_app
    ports:
      - "8080:80"
    environment:
      TIMEZONE: Europe/Madrid
    volumes:
      - glpi_data:/var/www/html/glpi
    depends_on:
      db:
        condition: service_healthy
    networks:
      - glpi_net
    restart: unless-stopped

volumes:
  db_data:
  glpi_data:

networks:
  glpi_net:

